/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Addmember.java
 *
 * Created on Dec 23, 2017, 8:41:38 AM
 */

package assignment;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Addmember extends javax.swing.JFrame {

    /** Creates new form Addmember */
    public Addmember() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        memname = new javax.swing.JTextField();
        memid = new javax.swing.JTextField();
        memcontext = new javax.swing.JTextField();
        membatch = new javax.swing.JTextField();
        savemem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comgender = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        homebut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("WELCOME FROM UIT (UNIVERSITY OF TECHNOLOGY) LIBRARY");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 60, 480, 19);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ADD NEW MEMBER");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("MEMBER NAME");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("MEMBER ID");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("CONTACT NO:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("BATCH NO:");

        memname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memnameActionPerformed(evt);
            }
        });
        memname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                memnameKeyTyped(evt);
            }
        });

        memcontext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                memcontextKeyTyped(evt);
            }
        });

        savemem.setBackground(new java.awt.Color(255, 255, 0));
        savemem.setFont(new java.awt.Font("Times New Roman", 1, 10));
        savemem.setText("SAVE");
        savemem.setBorderPainted(false);
        savemem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savememActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("GENDER");

        comgender.setFont(new java.awt.Font("Times New Roman", 0, 10));
        comgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE" }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton1.setText("BACK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(memname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(memid, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(memcontext, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(membatch, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(savemem)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(memname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(memid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(memcontext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(membatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savemem)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 120, 290, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\14f8e21b0792579e8ed2ac8a127eb1d5.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 90, 270, 340);

        homebut.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\kl1550-app-icon-home.png")); // NOI18N
        homebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutActionPerformed(evt);
            }
        });
        jPanel1.add(homebut);
        homebut.setBounds(560, 0, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memnameActionPerformed

    private void savememActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savememActionPerformed
       String memnam=memname.getText();
       String memi=memid.getText();
       String memco=memcontext.getText();
       String memba=membatch.getText();
        String comge=(String) comgender.getSelectedItem();
        member m= new member (memnam,memi,memco,memba,comge);
        membermethod mb= new membermethod();
        try {
            mb.save(m);
        } catch (IOException ex) {
            Logger.getLogger(Addmember.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Data are saved!!", null, 1);
        memname.setText("");
        memid.setText("");
        memcontext.setText("");
        membatch.setText("");
        comgender.setSelectedIndex(0);
    }//GEN-LAST:event_savememActionPerformed

    private void memcontextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memcontextKeyTyped
       char a=evt.getKeyChar();
       if(Character.isLetter(a)){
           evt.consume();
           JOptionPane.showMessageDialog(this, "It is only work for Intenger", null, 2);
       }
    }//GEN-LAST:event_memcontextKeyTyped

    private void memnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memnameKeyTyped
         char b=evt.getKeyChar();
       if(Character.isDigit(b)){
           evt.consume();
           JOptionPane.showMessageDialog(this, "It is only work for Alphabet", null, 2);
       }
    }//GEN-LAST:event_memnameKeyTyped

    private void homebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutActionPerformed
         Mainproject m=new Mainproject();
    m.setVisible(true);
    dispose();
    }//GEN-LAST:event_homebutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addmember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comgender;
    private javax.swing.JButton homebut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField membatch;
    private javax.swing.JTextField memcontext;
    private javax.swing.JTextField memid;
    private javax.swing.JTextField memname;
    private javax.swing.JButton savemem;
    // End of variables declaration//GEN-END:variables

}
