/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Dec 16, 2017, 12:40:18 AM
 */

package assignment;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class login extends javax.swing.JFrame {

    /** Creates new form login */
    public login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwo = new javax.swing.JTextField();
        loginbottom = new javax.swing.JButton();
        clearbuttom = new javax.swing.JButton();
        Exitbottom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 80, 90, 20);

        userna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernaActionPerformed(evt);
            }
        });
        jPanel1.add(userna);
        userna.setBounds(150, 80, 240, 20);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 70, 19);
        jPanel1.add(passwo);
        passwo.setBounds(150, 120, 240, 20);

        loginbottom.setBackground(new java.awt.Color(255, 255, 0));
        loginbottom.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        loginbottom.setText("Log In");
        loginbottom.setBorderPainted(false);
        loginbottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbottomActionPerformed(evt);
            }
        });
        jPanel1.add(loginbottom);
        loginbottom.setBounds(160, 160, 80, 27);

        clearbuttom.setBackground(new java.awt.Color(255, 255, 0));
        clearbuttom.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        clearbuttom.setText("Clear");
        clearbuttom.setBorderPainted(false);
        clearbuttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttomActionPerformed(evt);
            }
        });
        jPanel1.add(clearbuttom);
        clearbuttom.setBounds(240, 200, 80, 27);

        Exitbottom.setBackground(new java.awt.Color(255, 255, 0));
        Exitbottom.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        Exitbottom.setText("Exit");
        Exitbottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbottomActionPerformed(evt);
            }
        });
        jPanel1.add(Exitbottom);
        Exitbottom.setBounds(310, 250, 90, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\back ground.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbottomActionPerformed
    String name = userna.getText();
    String password = passwo.getText();
    ArrayList<namepass> q = new ArrayList();
    Logmethod p = new Logmethod();
        try {
            q = p.display();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    for(int i=0;i<q.size();i++)
    {
            String[] str=q.get(i).toString().split(":");
            for(int j=0;j<str.length;j++)
            {
                if(str[j].equals(name) && str[j+1].equals(password))
                {
                     Mainproject m = new Mainproject();
                     m.setVisible(true);
                     dispose();
                }
                else
                {
                    System.out.println("Your account is invalid.");
                    JOptionPane.showMessageDialog(this, str);
                }
            }

    }

    }//GEN-LAST:event_loginbottomActionPerformed

    private void clearbuttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttomActionPerformed
    userna.setText("");
    passwo.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearbuttomActionPerformed

    private void ExitbottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbottomActionPerformed
        System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_ExitbottomActionPerformed

    private void usernaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbottom;
    private javax.swing.JButton clearbuttom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbottom;
    private javax.swing.JTextField passwo;
    private javax.swing.JTextField userna;
    // End of variables declaration//GEN-END:variables

    private void ArrayList() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

}
