/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register.java
 *
 * Created on Dec 16, 2017, 2:54:38 AM
 */

package assignment;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    public Register() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unametxt = new javax.swing.JTextField();
        enterpasstxt = new javax.swing.JTextField();
        regbut = new javax.swing.JButton();
        clearbut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel2.setText("Enter Your Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 130, 19);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel3.setText("Enter Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 110, 19);
        jPanel1.add(unametxt);
        unametxt.setBounds(170, 80, 170, 20);
        jPanel1.add(enterpasstxt);
        enterpasstxt.setBounds(170, 130, 170, 20);

        regbut.setBackground(new java.awt.Color(255, 255, 0));
        regbut.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        regbut.setText("Register");
        regbut.setBorderPainted(false);
        regbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbutActionPerformed(evt);
            }
        });
        jPanel1.add(regbut);
        regbut.setBounds(170, 180, 90, 30);

        clearbut.setBackground(new java.awt.Color(255, 255, 0));
        clearbut.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        clearbut.setText("Clear");
        clearbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutActionPerformed(evt);
            }
        });
        jPanel1.add(clearbut);
        clearbut.setBounds(270, 180, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\back ground.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutActionPerformed
        unametxt.setText("");
       enterpasstxt.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearbutActionPerformed

    private void regbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbutActionPerformed
      String ur=unametxt.getText();
      String ep=enterpasstxt.getText();
      namepass n= new namepass(ur,ep);
      Logmethod lo= new Logmethod();
       try {
            lo.save(n);
        } catch (IOException ex) {
           Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
     // TODO add your handling code here:
    }//GEN-LAST:event_regbutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbut;
    private javax.swing.JTextField enterpasstxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regbut;
    private javax.swing.JTextField unametxt;
    // End of variables declaration//GEN-END:variables

}
